// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ex02.Data;

#nullable disable

namespace ex02.Migrations
{
    // Instantánea del modelo de la base de datos generada automáticamente.
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        // Construir el modelo de la base de datos.
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            // Definir la entidad Cliente en el modelo.
            modelBuilder.Entity("ex02.Models.Cliente", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<string>("Apellido")
                    .IsRequired()
                    .HasMaxLength(250)
                    .HasColumnType("varchar(250)");

                b.Property<string>("Direccion")
                    .IsRequired()
                    .HasMaxLength(250)
                    .HasColumnType("varchar(250)");

                b.Property<int?>("Dni")
                    .IsRequired()
                    .HasColumnType("int");

                b.Property<DateTime?>("Fecha")
                    .IsRequired()
                    .HasColumnType("datetime(6)");

                b.Property<string>("Nombre")
                    .IsRequired()
                    .HasMaxLength(250)
                    .HasColumnType("varchar(250)");

                b.HasKey("Id");

                b.ToTable("Clientes");
            });

            // Definir la entidad Video en el modelo.
            modelBuilder.Entity("ex02.Models.Video", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<int>("CliId")
                    .HasColumnType("int");

                b.Property<string>("Director")
                    .IsRequired()
                    .HasMaxLength(250)
                    .HasColumnType("varchar(250)");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(250)
                    .HasColumnType("varchar(250)");

                b.HasKey("Id");

                b.HasIndex("CliId");

                b.ToTable("Videos");
            });

            // Configurar la relación entre Video y Cliente en el modelo.
            modelBuilder.Entity("ex02.Models.Video", b =>
            {
                b.HasOne("ex02.Models.Cliente", "Cliente")
                    .WithMany("Videos")
                    .HasForeignKey("CliId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Cliente");
            });

            // Configurar la navegación a Videos desde la entidad Cliente en el modelo.
            modelBuilder.Entity("ex02.Models.Cliente", b =>
            {
                b.Navigation("Videos");
            });
#pragma warning restore 612, 618
        }
    }
}
